POLITICIANS =
  democrat: ["yC7dQ", "yAkxD", "yNDW2", "ykENm", "ymbLt", "yxCfv", "y5TA3", "y5K68", "yxYLt", "yxQTL", "y9vRK", "ysVVr", "yN3Bt", "yWJPb", "yCKXC", "yesaA", "ycj8S", "yBcrR", "y44Kv", "y9amA", "ySWGm", "y9GVX", "yc2UG", "yyqFc", "yyWTe", "yAwdm", "y9MeJ", "yeFk6", "yC6YP", "y5dX9", "yvJ5L", "ycsbA", "yBaDg", "yv76V", "yVf2v", "yTrrF", "yesTK", "yvmqD", "ymjrY", "yjR6D", "yA8qJ", "yv2by", "yeuVT", "ymUhb", "yvqyv", "yDfQQ", "y52NL", "yNdNr", "ykvQq", "yYDjm", "yCNXR", "ymJqs", "yPqFY", "ymRdY", "ySAtB", "yP7jq", "ySp46", "yVG4q", "yYqsb", "yH9UT", "yUkDm", "ycnaR", "yyFcq", "ycsdF", "y5Ngx", "ysPCf", "y7QEd", "ysY5S", "yebR7", "yxsu8", "yx9Yg", "yvnUg", "ycrrN", "y7wmQ", "y4x74", "ynj3q", "yBnnK", "yvjgd", "y5dBV", "y7cYD", "ykg77", "y9twW", "yktyV", "ynYne", "ySsur", "yWbHx", "yWLcY", "yTj8M", "y46nx", "yN5F2", "yB9TV", "yVbUs", "yWaTn", "yNYs5", "yPVHf", "yjkLj", "yePRr", "ynVpf", "yspyY", "yCFUw", "y4NWN", "yCbB8", "yBr8S", "ykPwg", "yvMTp", "yYndF", "y5Qs3", "yjgkC", "yWS5H", "yjUay", "yASuw", "yDJ2R", "yvFnq", "yHndK", "yNB4j", "y4nMH", "yHfsE", "yVtKn", "yspFs", "y4Q7V", "yWv8b", "yJ58A", "y52m8", "yDTsv", "yCm6r", "ySgUT", "ySsDJ", "yeFru", "yy5PE", "ynj6k"]
  neutral: ["y4VkS", "yD45S", "ymdSn", "yPjCY", "y74uE", "yjJU6", "yHUPL", "yTSuF", "y76L8", "yUgn5", "ynAFV", "yNGGb", "y42uA", "ykBXv", "yy7dW", "yPsGF", "yvCTh", "yBGd8", "yTXBn", "yH3RP", "yNrMC", "y78WF", "yBFBu", "yDFce", "yJQhC", "yVxFs", "yxrNE", "yCcmx", "y7bXn", "yCxK9", "yxXXy", "ymJ2e", "y9SvD", "ynXqF", "ymSjX", "yPhAm", "yDdQU", "yxWrM", "y4SP7", "ySswu", "ysy2h", "y7gDt", "ykTPA", "yHjBL", "y5MS2", "ykh9x", "yytYy", "yvEK9", "yPTG8", "yPYhe", "yYU4J", "yU8xt", "yHMeg", "yC9gX", "yHHrr", "y9FuP", "yCMAS", "yCLLt", "yPVAC", "yUR4F", "yCNHN", "yjgJP", "yWKgE", "yP46C", "yUKxM", "yJj9x", "y4yqm", "yS5tf", "y99Cr", "yTK7N", "y9qVn", "yUe6F", "yy7gL", "yPeEs", "y5T9D", "yYQG3", "ymssm", "yjjdf", "ySG3Y", "y4KEx", "yC82U", "yDvqa", "yxtKH", "yNCep", "yJCXm", "yD3TX", "yHbwK", "yHPxg", "yJPn9", "yVTdv", "yARs4", "yUkKU", "yPySe", "ymVRs", "yCUXY", "ySmsB", "yxgVj", "ykujW", "yxBnT", "ynwSA", "yApDu", "yJBCh", "yF5pS", "yScvN", "yxWkV", "ykWhT", "y9uqf", "yUfGe", "yVaQM", "yBSNB", "ym3Dd", "yxHn3", "ykvSu", "ykms7", "yANcE", "yYfhV", "yxTA9", "yWhW4", "yj7Vc", "ySQTp", "yAvhb", "ynAan", "y9T7V", "yCVPR", "yPygH", "yJCkY", "yxMhd", "ymBev", "yUyT5", "yUPRp", "yU2Bg", "yjLpV", "ykrjS", "yYYSc", "yyRk9", "y7MyU", "yYe5c", "yy7AD", "yPNSC", "yYRmP", "yCG9U", "y7sYn", "y56X4", "yyHbf", "yPWW8", "yHAxM", "yxa7e", "yeRwf", "yJfcA", "ynLJG", "yUwc9", "yJ6cw", "yFyVR", "yUW8c", "yjXPU", "yWNEK", "yjMjp", "y574w", "yvKHd", "yYYky", "yYRLk", "yPH3A", "y9dAW", "yCvY2", "y5q7S", "yU5bn", "yJjxD", "y59Gf", "yxEeu", "yNHXe", "ymrLq", "yxSNL", "y5SuU", "yjLv4", "yBhv4", "yYURv"]
  republican: ["ynGjR", "y4BaU", "yUbC6", "yCvCQ", "yyJMv", "yn6Qj", "yWqFr", "ykxdV", "yC2mT", "yBExA", "yxGMX", "yP9Rf", "yBjXt", "yV5K6", "y4Pun", "yDsBn", "yxnQ2", "yNTNp", "ySQhP", "yHhv5", "yUD28", "yDf3j", "yxKRD", "yBCJE", "yW3qv", "ye3Jq", "yBxv7", "ynk4A", "yDwFU", "yyH5s", "yDKsM", "yvEcj", "ynYwB", "yNEh5", "yH8fj", "ykUbK", "ysJdy", "yJFNg", "ycvRH", "ynJjE", "ykurE", "yJfGR", "yVeGQ", "yASXY", "ymETp", "yB3q9", "yA8pN", "yHBa5", "ySYba", "yCkJs", "ycJ9W", "ycTbM", "yYqrk", "y5LXc", "yjp7R", "y43pM", "yeGwG", "yBGCw", "yexyR", "yjukt", "yHw98", "yAxdF", "yCpUW", "yHXMs", "ymQwT", "yj8Xb", "yU9VN", "yNTqL", "yBy9A", "yH73g", "y4jB2", "y7AKd", "yAWSN", "ykHAU", "y9ste", "ysUSe", "y5RU3", "yUWaX", "yCvsU", "yvtPk", "y9MpC", "yUwKW", "y9frP", "yx3mu", "yTTqL", "yvRuV", "ykkRW", "ykCQP", "yTsAG", "yCEL7", "yV2ey", "ymqSf", "yjx9y", "y4JPn", "ySpF5", "yxcU7", "ykm65", "yW3b2", "yWwEe", "ynV9M", "yNjEg", "yvBmm", "y9WgQ", "yBU8C", "yjpYb", "yJMfh", "ykcnp", "yvSFN", "ycHWb", "yPxgm", "ysnCB", "yTBqv", "y7MVW"]

affiliations = {}  # id -> affiliation
_(POLITICIANS).each (politicians, affiliation) ->
  _(politicians).each (id) -> affiliations[id] = affiliation

window.get_affiliation = (entity_id) ->
  return affiliations[entity_id]